import { Link, useRouterState } from "@tanstack/react-router";
import { Activity, AlertTriangle, BarChart3, BedDouble, Bell, Boxes, BrainCircuit, ChevronDown, Cloud, LayoutDashboard, Map, Menu, Settings, Shuffle, Siren, Wifi } from "lucide-react";
import { Brand } from "./brand";
import { navItems } from "@/lib/demo-data";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Sidebar,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupContent,SidebarHeader,SidebarMenu,SidebarMenuButton,SidebarMenuItem,SidebarProvider,SidebarTrigger } from "@/components/ui/sidebar";
const icons=[LayoutDashboard,Boxes,BrainCircuit,Map,BedDouble,Siren,Shuffle,BarChart3,Bell,Settings];
export function AppShell({children,title,subtitle}:{children:React.ReactNode;title:string;subtitle:string}){const path=useRouterState({select:s=>s.location.pathname});return <SidebarProvider><div className="flex min-h-svh w-full bg-background"><Sidebar collapsible="icon" className="border-sidebar-border"><SidebarHeader className="h-20 justify-center border-b border-sidebar-border px-4"><Brand compact/></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupContent><SidebarMenu>{navItems.map(([to,label],i)=>{const Icon=icons[i];return <SidebarMenuItem key={to}><SidebarMenuButton asChild isActive={path===to} tooltip={label}><Link to={to}><Icon/><span>{label}</span></Link></SidebarMenuButton></SidebarMenuItem>})}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter className="border-t border-sidebar-border p-3"><div className="flex items-center gap-2 rounded-md bg-success-soft p-2 text-success"><Wifi className="size-4 shrink-0"/><div className="min-w-0 group-data-[collapsible=icon]:hidden"><p className="text-xs font-bold">Online</p><p className="truncate text-[10px]">All changes synced</p></div></div></SidebarFooter></Sidebar><main className="min-w-0 flex-1 pb-16 md:pb-0"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-border bg-background/95 px-4 backdrop-blur md:px-6"><div className="flex min-w-0 items-center gap-3"><SidebarTrigger className="size-9"/><div className="min-w-0"><h1 className="truncate text-lg font-bold">{title}</h1><p className="hidden truncate text-xs text-muted-foreground sm:block">{subtitle}</p></div></div><div className="flex items-center gap-2"><Badge className="hidden border-demo/20 bg-demo-soft text-demo shadow-none sm:flex">Demo environment</Badge><Button variant="ghost" size="icon" title="Notifications" asChild><Link to="/notifications"><Bell/></Link></Button><Button variant="outline" className="hidden gap-2 lg:flex">PHC Khordha<ChevronDown/></Button></div></header><div className="p-4 md:p-6">{children}</div></main><nav className="fixed inset-x-0 bottom-0 z-40 grid h-16 grid-cols-5 border-t border-border bg-background md:hidden">{navItems.slice(0,5).map(([to,label],i)=>{const Icon=icons[i];return <Link key={to} to={to} className="flex flex-col items-center justify-center gap-1 text-[10px] text-muted-foreground" activeProps={{className:"flex flex-col items-center justify-center gap-1 text-[10px] text-primary font-bold"}}><Icon className="size-4"/><span>{label.split(" ")[0]}</span></Link>})}</nav></div></SidebarProvider>}
