import { Link, useRouterState } from "@tanstack/react-router";
import { BadgeCheck, Building2, UserCircle, Users as UsersIcon, BarChart3, BedDouble, Bell, Boxes, BrainCircuit, ChevronDown, LayoutDashboard, Map, Settings, Shuffle, Siren, Wifi, type LucideIcon } from "lucide-react";
import { Brand } from "./brand";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Sidebar,SidebarContent,SidebarFooter,SidebarGroup,SidebarGroupContent,SidebarHeader,SidebarMenu,SidebarMenuButton,SidebarMenuItem,SidebarProvider,SidebarTrigger } from "@/components/ui/sidebar";
import { useAccount } from "@/hooks/use-account";
import { ProfileMenu } from "./profile-menu";
type Nav=[string,string,LucideIcon];
const staffNav:Nav[]=[["/dashboard","Dashboard",LayoutDashboard],["/resources","Facilities",BedDouble],["/inventory","Inventory",Boxes],["/predictions","AI Predictions",BrainCircuit],["/redistribution","Redistribution",Shuffle],["/emergency","Emergency SOS",Siren],["/notifications","Notifications",Bell],["/analytics","Analytics",BarChart3],["/profile","Profile",UserCircle],["/settings","Settings",Settings]];
const userNav:Nav[]=[["/dashboard","Dashboard",LayoutDashboard],["/network","Facilities",Building2],["/network","Map",Map],["/emergency","Emergency",Siren],["/notifications","Notifications",Bell],["/profile","Profile",UserCircle],["/settings","Settings",Settings]];
const adminNav:Nav[]=[["/dashboard","Dashboard",LayoutDashboard],["/network","Facilities",Building2],["/inventory","Inventory",Boxes],["/predictions","AI Predictions",BrainCircuit],["/redistribution","Redistribution",Shuffle],["/emergency","Emergency",Siren],["/analytics","Analytics",BarChart3],["/admin/verifications","Hospital Verification",BadgeCheck],["/admin/verifications","Users",UsersIcon],["/notifications","Notifications",Bell],["/settings","Settings",Settings]];
function useNav(){const {data}=useAccount();if(!data)return userNav.slice(0,1);return data.isAdmin?adminNav:data.canManageHospital?staffNav:userNav}
import { useDueReminders } from "./reminders";
function ReminderDot(){const {visible}=useDueReminders();const {data}=useAccount();const n=(data?.canManageHospital?visible.length:0)+3;return <span aria-label={`${n} unread notifications`} className="absolute -right-0.5 -top-0.5 flex size-4 items-center justify-center rounded-full bg-destructive text-[10px] font-bold text-destructive-foreground">{n}</span>}
export function AppShell({children,title,subtitle}:{children:React.ReactNode;title:string;subtitle:string}){const path=useRouterState({select:s=>s.location.pathname});const nav=useNav();return <SidebarProvider><div className="flex min-h-svh w-full bg-background"><Sidebar collapsible="icon" className="border-sidebar-border"><SidebarHeader className="h-20 justify-center border-b border-sidebar-border px-4"><Brand compact/></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupContent><SidebarMenu>{nav.map(([to,label,Icon])=>{return <SidebarMenuItem key={label}><SidebarMenuButton asChild isActive={path===to} tooltip={label}><Link to={to}><Icon/><span>{label}</span></Link></SidebarMenuButton></SidebarMenuItem>})}</SidebarMenu></SidebarGroupContent></SidebarGroup></SidebarContent><SidebarFooter className="border-t border-sidebar-border p-3"><div className="flex items-center gap-2 rounded-md bg-success-soft p-2 text-success"><Wifi className="size-4 shrink-0"/><div className="min-w-0 group-data-[collapsible=icon]:hidden"><p className="text-xs font-bold">Online</p><p className="truncate text-[10px]">All changes synced</p></div></div></SidebarFooter></Sidebar><main className="min-w-0 flex-1 pb-16 md:pb-0"><header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-border bg-background/95 px-4 backdrop-blur md:px-6"><div className="flex min-w-0 items-center gap-3"><SidebarTrigger className="size-9"/><div className="min-w-0"><h1 className="truncate text-lg font-bold">{title}</h1><p className="hidden truncate text-xs text-muted-foreground sm:block">{subtitle}</p></div></div><div className="flex items-center gap-2"><Badge className="hidden border-demo/20 bg-demo-soft text-demo shadow-none sm:flex">Demo environment</Badge><Button variant="ghost" size="icon" title="Notifications" asChild><Link to="/notifications" className="relative"><Bell/><ReminderDot/></Link></Button><ProfileMenu/></div></header><div className="p-4 md:p-6">{children}</div></main><nav className="fixed inset-x-0 bottom-0 z-40 grid h-16 grid-cols-5 border-t border-border bg-background md:hidden">{nav.slice(0,5).map(([to,label,Icon])=>{return <Link key={label} to={to} className="flex flex-col items-center justify-center gap-1 text-[10px] text-muted-foreground" activeProps={{className:"flex flex-col items-center justify-center gap-1 text-[10px] text-primary font-bold"}}><Icon className="size-4"/><span>{label.split(" ")[0]}</span></Link>})}</nav></div></SidebarProvider>}
