import { Activity, AlertTriangle, ArrowRight, BedDouble, BrainCircuit, Building2, CheckCircle2, Clock, Database, FileDown, HeartPulse, MapPin, PackageCheck, Route, ShieldCheck, Sparkles, Stethoscope, WifiOff } from "lucide-react";
import { Area,AreaChart,CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis,Bar,BarChart } from "recharts";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { DemoBadge,StatusBadge } from "./status";
import { facilities,inventory } from "@/lib/demo-data";
const trend=[{d:"1 Sep",actual:520,forecast:520},{d:"5 Sep",actual:440,forecast:450},{d:"9 Sep",actual:365,forecast:380},{d:"13 Sep",actual:280,forecast:300},{d:"17 Sep",actual:205,forecast:220},{d:"21 Sep",actual:120,forecast:145},{d:"25 Sep",forecast:68}];
const activity=[{d:"Mon",inventory:42,emergency:3},{d:"Tue",inventory:58,emergency:5},{d:"Wed",inventory:48,emergency:2},{d:"Thu",inventory:71,emergency:7},{d:"Fri",inventory:64,emergency:4},{d:"Sat",inventory:38,emergency:2},{d:"Sun",inventory:44,emergency:3}];
export function PageIntro({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:React.ReactNode}){return <div className="mb-6 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div>{eyebrow&&<p className="mb-2 text-xs font-bold uppercase text-primary">{eyebrow}</p>}<h2 className="font-display text-2xl font-bold md:text-3xl">{title}</h2><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{description}</p></div>{action}</div>}
export function Kpis(){return <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[[Building2,"Facilities connected","1,248","+18 this month"],[Database,"Resources monitored","18,640","96.8% reporting"],[AlertTriangle,"Predicted shortages","27","6 critical"],[Siren,"Active emergencies","3","2 responses confirmed"]].map(([I,label,value,note])=>{const Icon=I as typeof Building2;return <Card key={label as string}><CardContent className="p-5"><div className="flex items-start justify-between"><div className="flex size-9 items-center justify-center rounded-md bg-primary-soft text-primary"><Icon className="size-4"/></div><DemoBadge/></div><p className="mt-5 text-3xl font-bold">{value as string}</p><p className="mt-1 text-sm font-medium">{label as string}</p><p className="mt-1 text-xs text-muted-foreground">{note as string}</p></CardContent></Card>})}</div>}
export function PredictionChart(){return <div className="h-64 w-full"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend} margin={{top:12,right:12,left:-20,bottom:0}}><defs><linearGradient id="forecastFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--color-primary)" stopOpacity={.2}/><stop offset="1" stopColor="var(--color-primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--color-border)"/><XAxis dataKey="d" tickLine={false} axisLine={false} fontSize={11}/><YAxis tickLine={false} axisLine={false} fontSize={11}/><Tooltip/><Area type="monotone" dataKey="actual" stroke="var(--color-success)" fill="url(#forecastFill)" strokeWidth={2}/><Line type="monotone" dataKey="forecast" stroke="var(--color-destructive)" strokeDasharray="5 4" strokeWidth={2}/></AreaChart></ResponsiveContainer></div>}
export function InventoryTable(){return <div className="overflow-hidden border border-border"><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead className="bg-muted/70 text-xs uppercase text-muted-foreground"><tr>{["Medicine","Current stock","Daily usage","Reorder level","Days remaining","Risk","Last updated"].map(x=><th key={x} className="px-4 py-3 font-semibold">{x}</th>)}</tr></thead><tbody>{inventory.map(i=><tr key={i.name} className="border-t border-border"><td className="px-4 py-4 font-semibold">{i.name}</td><td className="px-4 py-4">{i.stock} units</td><td className="px-4 py-4">{i.usage}/day</td><td className="px-4 py-4">{i.reorder}</td><td className="px-4 py-4 font-bold">{i.days}</td><td className="px-4 py-4"><StatusBadge status={i.risk}/></td><td className="px-4 py-4 text-muted-foreground">{i.updated}</td></tr>)}</tbody></table></div></div>}
export function AIRecommendation(){return <Card className="border-primary/25 bg-primary-soft/45"><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle className="flex items-center gap-2 text-base"><Sparkles className="size-4 text-primary"/>Swasthya AI recommendation</CardTitle><DemoBadge/></div></CardHeader><CardContent><p className="text-sm leading-6">Transfer approximately <strong>150 ORS sachets</strong> from Capital Hospital to PHC Khordha. The source maintains 24 days of cover after transfer.</p><div className="mt-4 flex flex-wrap gap-2 text-xs text-muted-foreground"><span>Based on available system data</span><span>•</span><span>Confidence 87%</span><span>•</span><span>Model demo-v1.0</span></div><div className="mt-4 flex items-center gap-2 text-xs font-bold uppercase text-warning-foreground"><ShieldCheck className="size-4"/>Requires human approval</div></CardContent></Card>}
export function AnalyticsChart(){return <div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={activity} margin={{top:12,right:10,left:-20,bottom:0}}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--color-border)"/><XAxis dataKey="d" axisLine={false} tickLine={false}/><YAxis axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="inventory" fill="var(--color-primary)" radius={[3,3,0,0]}/><Bar dataKey="emergency" fill="var(--color-warning)" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div>}
export function FacilityList(){return <div className="grid gap-3 lg:grid-cols-2">{facilities.map(f=><Card key={f.id}><CardContent className="flex items-center justify-between gap-4 p-4"><div className="min-w-0"><div className="flex items-center gap-2"><h3 className="truncate font-bold">{f.name}</h3><StatusBadge status={f.status}/></div><p className="mt-1 text-xs text-muted-foreground">{f.type} · {f.district}</p><div className="mt-3 flex gap-4 text-xs"><span><strong>{f.beds}</strong> beds</span><span><strong>{f.doctors}</strong> doctors</span><span>Updated {f.sync}</span></div></div><Button variant="outline" size="icon" title="View facility"><ArrowRight/></Button></CardContent></Card>)}</div>}
export const sectionIcons={Activity,AlertTriangle,BedDouble,BrainCircuit,CheckCircle2,Clock,FileDown,HeartPulse,MapPin,PackageCheck,Route,Stethoscope,WifiOff};
